language: java

script:
  - cd narrative-scalatest && ./gradlew clean test
  - cd examples && ./gradlew clean test

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
